id: P4A2FAFEA
initial_creation_type: input
source_metadata:
  title: Alak Zenkar Rinpoche
  language: bo
  description: 'Texts by and about the great scholar Alak Zenkar Rinpoche Thupten
    Nyima (a lags gzan dkar thub bstan nyi ma, b.1943):'
  volume:
    ac45751658ae4099b9aadd5828f365a6:
      title: Biography of Jamgön Kongtrul Lodrö Thaye
      parent: Biography
    57ea8eecb485447dafb1727c72dbf767:
      title: Biography of Jamyang Khyentse Wangpo
      parent: Biography
    e3a2fd209158468fb5150ff2a8870864:
      title: Biography of Patrul Rinpoche
      parent: Biography
    cf2ee437e8e54107950d3ebcc9102a2a:
      title: Biography of Shechen Gyaltsab Gyurme Pema Namgyal
      parent: Biography
    fd08172772104b7ab8624db8f9f3e617:
      title: Brief Biography of Drakkar Lobzang Palden
      parent: Biography
    1c8fadf86ad74086b0b6d72f8af485a8:
      title: Brief Biography of Kharlek Tulku Pema Kunzang Rangdrol
      parent: Biography
    82c42634e1b64ecfaa0006ca55bf903b:
      title: Brief Biography of Tāranātha
      parent: Biography
    592491adf29445eb9042935c5a9d4f2d:
      title: A Brief Presentation of the Nine Vehicles
      parent: Buddhist Philosophy
    cab881e846914fe5912721b04ad5896b:
      title: Long Life Prayer for Alak Zenkar Rinpoche
      parent: Long Life Prayers
    63426ff1d1fd431995a25e0c8e9b3e5b:
      title: Long Life Prayer for Patrick Gaffney (Yeshé Wangyal)
      parent: Long Life Prayers
    3694ec32b7fd468b9fd7dd70894c5f14:
      title: Prayer for the Long Life of Alak Zenkar Rinpoche, the Incarnation of
        Do Khyentsé Yeshé Dorjé
      parent: Long Life Prayers
    e4ce6ff149fc42b4a5d975f9cbca5d5d:
      title: 'Bodhicaryāvatāra: Teachings and Overview'
      parent: Oral Teachings
    7ef5a22a557b432f80c83a5c44e823b9:
      title: Light from the Wisdom Sun
      parent: Prayers and Practices
    8bbbddd438584bb1be736408c02734a1:
      title: A Prayer for the Swift Rebirth of Tenpai Nyima Rinpoche
      parent: Swift Rebirth Prayers
    489fd64f099346139b415df151fde380:
      title: Prayer for Swift Rebirth of the Fourth Dodrupchen Rinpoche
      parent: Swift Rebirth Prayers
created_at: '2022-02-28T22:37:59.749310'
last_modified_at: '2022-02-28T22:37:59.749313'
statistics:
  total_words: 10952
  total_non_words: 1130
quality:
  non_words_ratio: 0.1
